name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm cache
      uses: actions/cache@v3
      id: node-modules
      with:
        path: node_modules/
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache

    - name: Install dependencies
      if: steps.node-modules.outputs.cache-hit != 'true'
      run: npm i --no-audit

    - name: Generate Vuepress site
      run: |
        npm run docs:build

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
        ARGS: "-avz --delete"
        SOURCE: ".vuepress/dist/"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}

    - name: Telegram notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TG_BOT_TOKEN }} #use bot @BotFather
        chatId: ${{ secrets.TG_CHAT_ID }} #use bot @userinfobot
        jobStatus: ${{ job.status }}
        skipSuccess: false